#! /usr/bin/sh


### this should be change to reading input file name from standard input not hard coded in this!!!


# on CBCB server
# dir <- /cbcb/project-scratch/fdorri/Data/sra
# sh fastq2sam.sh par
## par = input file name
# or
#qsub -q xlarge -l mem=120G,walltime=72:00:00 run.sh -N bismark


input=$1

echo "Hello world"

#######  download sra:
#wget ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR101/SRR1015705/SRR1015705.sra -O /cbcb/project-scratch/fdorri/Data/sra/SRR1015705.sra &


#wget ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP052/SRR052746/SRR1769152.sra -O /cbcb/project-scratch/fdorri/Data/sra/SRR1769152.sra &

####### sra to fastq:
#/cbcb/project2-scratch/fdorri/sratoolkit.2.3.5-2-centos_linux64/bin/fastq-dump -A /cbcb/project2-scratch/fdorri/Data/sra/SRR1769243.sra -O /cbcb/project2-scratch/fdorri/Data/sra/fastq &

inputdir="/cbcb/project-scratch/fdorri/Data/sra/fastq/${input}"
outputfile="${input}.sorted.sam"

echo "start splitting"
#Splitting the fastq files to smaller one so that we can easily run bismark
split -l 40000000 ${inputdir} /cbcb/project2-scratch/fdorri/Data/sra/fastq/h_
echo "splitting finished"



#renaming the file, adding .fastq extention
cd /cbcb/project2-scratch/fdorri/Data/sra/fastq/
for f in h_*
do
mv $f  ${f}.fastq
done
echo "renaming file finished"




#running Bismark and align every fastq files to selected genome using bismark
cd /cbcb/project2-scratch/fdorri/Data/sra/fastq/
for f in h_*
do
/cbcb/project2-scratch/fdorri/bismark_v0.11.1/bismark -n 1 -l 50 -o /cbcb/project2-scratch/fdorri/Data/sra/sam/ /cbcb/project2-scratch/fdorri/Data/refseq/ /cbcb/project2-scratch/fdorri/Data/sra/fastq/${f}
#/cbcb/project2-scratch/fdorri/bismark_v0.11.1/bismark -n 1 -l 50 -o /cbcb/project2-scratch/fdorri/Data/sra/sam/ /cbcb/project2-scratch/fdorri/Data/refseq/ /cbcb/project2-scratch/fdorri/Data/sra/fastq/h_aa.fastq

/cbcb/project2-scratch/fdorri/bismark_v0.14.5/bismark --bowtie2 -o /cbcb/project2-scratch/fdorri/Data/sra/sam/ /cbcb/project2-scratch/fdorri/Data/refseq/ /cbcb/project2-scratch/fdorri/Data/sra/fastq/h_aa.fastq

done

echo "bismark finished"


#sorting sam files, first need to change to bam and then sort
cd /cbcb/project2-scratch/fdorri/Data/sra/sam/
for f in h_*.sam
do
samtools view -Shu $f | samtools sort -  sorted.${f}
done

echo "sam to sorted bam finished"


#merge all the bam files into a single bam
samtools merge  finall_h.bam sorted.h_*.bam

echo "merging sorted bams finished"


# get final sorted sam from sorted bam
samtools view finall_s.bam -h -o ${outputfile}
echo "sorted bam to final sorted sam file finished"



#### ruunig for another data set #####
#######################################################################################

#Splitting the fastq files to smaller one so that we can easily run bismark
#split -l 40000000 /cbcb/project-scratch/fdorri/Data/sra/fastq/SRR1020523.fastq /cbcb/project-scratch/fdorri/Data/sra/fastq/a_

#renaming the file, adding .fastq extention
#cd /cbcb/project-scratch/fdorri/Data/sra/fastq/
#for f in a_*
#do
#mv $f  ${f}.fastq
#done

#running Bismark and align every fastq files to selected genome using bismark
#cd /cbcb/project-scratch/fdorri/Data/sra/fastq/
#for f in a_*
#do
#/cbcb/project-scratch/fdorri/bismark_v0.11.1/bismark -n 1 -l 50 -o /cbcb/project-scratch/fdorri/Data/sra/sam/ /cbcb/project-scratch/fdorri/Data/refseq/ /cbcb/project-scratch/fdorri/Data/sra/fastq/${f}
#done


#sorting sam files, first need to change to bam and then sort
#cd /cbcb/project-scratch/fdorri/Data/sra/sam/
#for f in b_*.sam
#do
#samtools view -Shu $f | samtools sort -  sorted.${f}
#done


#merge all the bam files into a single bam
#samtools merge  finall_a.bam sorted.a_*.bam

# get final sorted sam from sorted bam
#samtools view finall_a.bam -h -o SRR1020523.sorted.sam

